### PR TITLE
add eslint-plugin-unicorn

### PR DESCRIPTION
**Pull request by dtinth**
image

also add a hackpicked set of rules to enforce more consistency (most rules can be autofixed)

### CODE REVIEW

**Comment by dtinth** [comment]
@Leomotors i tried it, it clashes with Prettier and some rules i do not agree with.

**Review by Leomotors — APPROVED** [review]

**Comment by beam41** [comment]
Does adding [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) help with rules clash

**Comment by dtinth** [comment]
@beam41 oh you’re right, have to put the prettier config at the bottom

but there are other rules i don’t agree with as well. maybe we can try the recommended preset in later pr.

**Comment by beam41** [comment]
I think using recommend and disable some rules would be better, but I don't know how many rules you disagree with lol.

**Comment by dtinth** [comment]
@beam41 i updated to use recommended unicorn config.

overrides:

- `'unicorn/no-null'` - null is shorter than undefined and often used in patterns like `JSON.stringify(x, null, 2)`.
- `'unicorn/filename-case'` - updated to use camelCase and PascalCase

**Review by beam41 — APPROVED** [review]

**Review by narze — APPROVED** [review]

**Review by narze — APPROVED** [review]

**Pull request merged**
